#
# Validation page:
#   https://lint.travis-ci.org/
#
# If you want to skip CI for a particular commit, add the following line to the commit message:
#   [ci skip]
# or 
#   [skip ci]
# (see https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build)
#
# Fix for ensuring that a tagged commit leads to an auto-deployment of the result
#   https://github.com/travis-ci/travis-ci/issues/2498

# The following setting seems to block the auto-deployment after a succesful build.
# Configure which branches to use
#branches:
#  only:
#    master

language: generic

###############################################################################
install:
  - travis_retry wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  - export PATH="/opt/texbin:$PATH"

###############################################################################
before_script:
  # Check texlive version
  - tlmgr version -v
  # Check which tex packages we have available
  - tlmgr info --only-installed ||
        echo "Couldn't retrieve the texlive package list!"

###############################################################################
script:
  - cd Handbook/org.moflon.doc.handbook/src
  - pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile &&
    bibtex eMoflonHandbook_mainFile &&
    pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile &&
    pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile
  - cp eMoflonHandbook_mainFile.pdf eMoflonHandbook.pdf

#after_success:
#  # Check that current branch is master, or quit
#  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. Current branch is $TRAVIS_BRANCH"; exit 0; fi
#  - echo "Deploying build $TRAVIS_BUILD_NUMBER"  
  
###############################################################################
# Deployment after successful build
# 
# Official docu: https://docs.travis-ci.com/user/deployment/releases/
# See also: https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/33109519#33109519
#
# How to deploy (experimental!):
# 1. Commit your code:            e.g., git commit -am "Intermediate release"
# 2. Create a tag:                e.g., git tag -a -m "Intermediate release" intermediate-release_2017-01-19
# 3. Push the commit and the tag: e.g., git push origin master --tags
# 4. Travis CI will create a new release of the documentation 
#
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file:
    - Handbook/org.moflon.doc.handbook/src/eMoflonHandbook.pdf
  skip_cleanup: true
  on:
#    repo: eMoflon/emoflon-docu
    tags: true
    all_branches: true