#
# Validation page:
# https://lint.travis-ci.org/
#
# If you want to skip CI for a particular commit, add the following line to the commit message:
# [ci skip]
# (see https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build)

# Configure which branches to use
branches:
  only:
    master

language: generic

###############################################################################
install:
  - travis_retry wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  - export PATH="/opt/texbin:$PATH"

###############################################################################
before_script:
  # Check texlive version
  - tlmgr version -v
  # Check which tex packages we have available
  - tlmgr info --only-installed ||
        echo "Couldn't retrieve the texlive package list!"

###############################################################################
script:
  # Use this for PDF with bibtex citations
  - cd Handbook/org.moflon.doc.handbook/src
  - pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile &&
    bibtex eMoflonHandbook_mainFile &&
    pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile &&
    pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile
