#
# Validation page:
#   https://lint.travis-ci.org/
#
# If you want to skip CI for a particular commit, add the following line to the commit message:
#   [ci skip]
# or 
#   [skip ci]
# (see https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build)
#

# Configure which branches to use
branches:
  only:
    master

language: generic

###############################################################################
install:
  - travis_retry wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
  - export PATH="/opt/texbin:$PATH"

###############################################################################
before_script:
  # Check texlive version
  - tlmgr version -v
  # Check which tex packages we have available
  - tlmgr info --only-installed ||
        echo "Couldn't retrieve the texlive package list!"

###############################################################################
script:
  - cd Handbook/org.moflon.doc.handbook/src
  - pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile &&
    bibtex eMoflonHandbook_mainFile &&
    pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile &&
    pdflatex -halt-on-error -interaction nonstopmode eMoflonHandbook_mainFile
  - cp eMoflonHandbook_mainFile.pdf eMoflonHandbook.pdf

###############################################################################
# Deployment after successful build
# 
# Official docu: https://docs.travis-ci.com/user/deployment/releases/
# See also: https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/33109519#33109519
#
# How to deploy (experimental!):
# 1. Commit your code
# 2. Create a tag
# 3. Push the commit and the tag -> Travis CI will create a new release of the documentation 
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file:
    - Handbook/org.moflon.doc.handbook/src/eMoflonHandbook.pdf
  skip_cleanup: true
  on:
    tags: true
    all_branches: true